# Generated by Django 4.2.9 on 2024-03-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='body_fat',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='height',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='target',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='weight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
